version: "3.9"
services:
  api:
    build: .
    command: uv run uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./frontend:/app/frontend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`ml.skyrodev.ru`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik_default"
